# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Squares the function
#'
#' @param x First value
#' @return Product of v1 and v2
#' @export
square <- function(x) {
    .Call('_testRpkg_square', PACKAGE = 'testRpkg', x)
}

